// MongoDB Playground
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.
import {v4 as uuidv4} from 'uuid';
uuidv4();

// The current database to use.
const booksDataBase = "MY_BOOKS_DB";
use(booksDataBase);
const myCollection = "BOOKS";

// Find a document in a collection.
//db.getCollection("BOOKS").findOne({});
const  dateRead = new Date();
const dates = (dateRead.getDay, dateRead.getMonth, dateRead.getFullYear);

db.myCollection.insertMany([
    {
        "id": 101,
        "bookcover": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZyEUScaTnehxsV6AZzsPhtro2xxn6QCwlA5J700ws1Mccylkw",
        "title": "A Court of Thorns and Roses",
        "author": "Sarah J. Maas",
        "genre": "Fiction",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast, but one of the lethal, immortal faeries who once ruled her world. At least, he's not a beast all the time. As she adapts to her new home, her feelings for the faerie, Tamlin, transform from icy hostility into a fiery passion that burns through every lie she's been told about the beautiful, dangerous world of the Fae. But something is not right in the faerie lands. An ancient, wicked shadow is growing, and Feyre must find a way to stop it, or doom Tamlin-and his world-forever.",
        "pages": 432,
        "published": 2015,
        "dateread": dates,
        "customlists":1
    },
    {
        "id": 102,
        "bookcover": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQabffz3fxoX2JS1y8Bydu_1S5Fgk_cQfZLA&s",
        "title": "The Lord of the Rings",
        "author": "John Ronald Reuel Tolkien",
        "genre": "Fantasy",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, The Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell, by chance, into the hands of the hobbit, Bilbo Baggins. From his fastness in the Dark Tower of Mordor, Sauron's power spread far and wide. He gathered all the Great Rings to him, but ever he searched far and wide for the One Ring that would complete his dominion. On his eleventy-first birthday Bilbo disappeared, bequeathing to his young cousin Frodo the Ruling Ring and a perilous quest --- to journey across Middle-earth, deep into the shadow of the Dark Lord, and destroy the Ring by casting it into the Cracks of Doom. THE LORD OF THE RINGS tells of the great quest undertaken by Frodo and the Fellowship of the Ring: Gandalf the Wizard, Merry, Pippin, and Sam, Gimli the Dwarf, Legolas the Elf, Boromir of Gondor, and a tall, mysterious stranger called Strider.",
        "pages": 1137,
        "published": 2001,
        "dateread": dates,
        "customlists":2,
    },
    {
        "id": 103,
        "bookcover": "https://m.media-amazon.com/images/I/71bXcusLgJL._AC_UF1000,1000_QL80_.jpg",
        "title": "Fourth Wing",
        "author": "Rebecca Yarros",
        "genre": "Fantasy",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "Violet Sorrengail expected to live a quiet life surrounded by books, until she was forced onto the world's deadliest training ground. Now she must fight to join the army's elite: dragon riders. But dragons don't choose fragile riders, they incinerate them, and when your body breaks as easily as Violet's does - death is only a heartbeat away. Many cadets would kill Violet to better their own chances of success; the rest would kill her just because of her last name . . . including the ruthless Xaden Riorson, her family's greatest enemy. With the odds stacked against her, Violet must use every edge her wits can give her just to see the next sunrise, because once you enter Basgiath War College, there are only two ways out: GRADUATE OR DIE",
        "pages": 576,
        "published": 2023,
        "dateread": dates,
        "customlists": 1,
    },
    {
        "id": 104,
        "bookcover": "https://m.media-amazon.com/images/I/61WxYof082L._AC_UF1000,1000_QL80_.jpg",
        "title": "Chain of Gold",
        "author": "Cassandra Clare",
        "genre": "Fantasy",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "Cordelia Carstairs is a Shadowhunter, a warrior trained since childhood to battle demons. When her father is accused of a terrible crime, she and her brother travel to London in hopes of preventing the family’s ruin. Cordelia’s mother wants to marry her off, but Cordelia is determined to be a hero rather than a bride. Soon Cordelia encounters childhood friends James and Lucie Herondale and is drawn into their world of glittering ballrooms, secret assignations, and supernatural salons, where vampires and warlocks mingle with mermaids and magicians. All the while, she must hide her secret love for James, who is sworn to marry someone else. But Cordelia’s new life is blown apart when a shocking series of demon attacks devastate London. These monsters are nothing like those Shadowhunters have fought before—these demons walk in daylight, strike down the unwary with incurable poison, and seem impossible to kill. London is immediately quarantined. Trapped in the city, Cordelia and her friends discover that their own connection to a dark legacy has gifted them with incredible powers—and forced a brutal choice that will reveal the true cruel price of being a hero.",
        "pages": 624,
        "published": 2020,
        "dateread": dates,
        "customlists": 2,
    },
    {
        "id": 105,
        "bookcover": "https://m.media-amazon.com/images/I/91qirYaUzrL._AC_UF894,1000_QL80_.jpg",
        "title": "Iron Flame",
        "author": "Rebecca Yarros",
        "genre": "Fantasy",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "Against all odds, Violet Sorrengail made it through her first year at Basgiath War College, but now, the real training begins. The stakes are higher than ever, and a determination to survive won't be enough this time. When a powerful new enemy threatens everything she cares about, including the man she loves, Violet must do whatever it takes to keep their secrets safe. One wrong move could have horrifying consequences - and as the web of lies spun by those in charge starts to unravel, nothing, not even dragon fire, may be enough to save them in the end. THE DEADLY SECOND YEAR AT BASGIATH AWAITS",
        "pages": 800,
        "published": 2023,
        "dateread": dates,
        "customlists": [],
    },
    { 
        "id": 106,
        "bookcover": "https://m.media-amazon.com/images/I/81IP261kwlL._AC_UF1000,1000_QL80_.jpg",
        "title": "Chain of Iron",
        "author": "Cassandra Clare",
        "genre": "Fantasy",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "Cordelia Carstairs seems to have everything she ever wanted. She’s engaged to marry James Herondale, the boy she has always loved; she has a new life in London with her best friend Lucie; and she bears the sword Cortana, a legendary hero’s blade. But the truth is far grimmer. Cordelia’s marriage is a lie, arranged to save her reputation, while James remains in love with the Grace Blackthorn. Cortana burns her when she touches it. And a serial murderer is targeting the Shadowhunters of London, killing under cover of darkness, then vanishing without a trace. Now Cordelia, James, and Lucie must follow the trail of the killer through the city’s most dangerous streets. All the while, each is keeping a shocking secret: Lucie, that she is attempting to raise the dead; Cordelia, that she has sworn a dangerous oath of loyalty to a mysterious power; and James, that he himself may be the killer they seek.",
        "pages": 688,
        "published": 2023,
        "dateread": dates,
        "customlists": 4,
    },
    {
        "id": 107,
        "bookcover": "https://m.media-amazon.com/images/I/81dY-4XtCXL._UF1000,1000_QL80_.jpg",
        "title": "Onyx Storm",
        "author": "Rebecca Yarros",
        "genre": "Fantasy",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "After nearly eighteen months at Basgiath War College, Violet Sorrengail knows there’s no more time for lessons. No more time for uncertainty. Because the battle has truly begun, and with enemies closing in from outside their walls and within their ranks, it’s impossible to know who to trust. Now Violet must journey beyond the failing Aretian wards to seek allies from unfamiliar lands to stand with Navarre. The trip will test every bit of her wit, luck, and strength, but she will do anything to save what she loves—her dragons, her family, her home, and him. Even if it means keeping a secret so big, it could destroy everything. They need an army. They need power. They need magic. And they need the one thing only Violet can find—the truth. But a storm is coming...and not everyone can survive its wrath.",
        "pages": 544,
        "published": 2025,
        "dateread": dates,
        "customlists": 4,
    },
    {
        "id": 108,
        "bookcover": "https://m.media-amazon.com/images/I/61pjyMrRCSL._AC_UF1000,1000_QL80_.jpg",
        "title": "It",
        "author": "Stephen King",
        "genre": "Horror",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "It by Stephen King is a gripping horror novel that follows a group of outcast kids in Derry, Maine as they confront an ancient, shape-shifting evil that preys on the town's children.",
        "pages": 1138,
        "published": 1986,
        "dateread": dates,
        "customlists": 4,
    },
    {
        "id": 109,
        "bookcover": "https://m.media-amazon.com/images/I/91PtVqr8spL.jpg",
        "title": "Chain of Thorns",
        "author": "Cassandra Clare",
        "genre": "Fantasy",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "Cordelia Carstairs has lost everything that matters to her. In only a few short weeks, she has seen her father murdered, her plans to become parabatai with her best friend, Lucie, destroyed, and her marriage to James Herondale crumble before her eyes. Even worse, she is now bound to an ancient demon, Lilith, stripping her of her power as a Shadowhunter. After fleeing to Paris with Matthew Fairchild, Cordelia hopes to forget her sorrows in the city's glittering nightlife. But reality intrudes when shocking news comes from home: Tatiana Blackthorn has escaped the Adamant Citadel, and London is under new threat by the Prince of Hell. Cordelia returns to a London riven by chaos and dissent. Cordelia longs to protect James, but is torn between a love for James she has long believed hopeless, and the possibility of a new life with Matthew.",
        "pages": 784,
        "published": 2023,
        "dateread": dates,
        "customlists": 4,
    },
    {
        "id": 110,
        "bookcover": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Carrie_%281974%29_front_cover%2C_first_edition.jpg",
        "title": "Carrie",
        "author": "Stephen King",
        "genre": "Horror",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "The story of misfit high-school girl, Carrie White, who gradually discovers that she has telekinetic powers. Repressed by a domineering, ultra-religious mother and tormented by her peers at school, her efforts to fit in lead to a dramatic confrontation during the senior prom. ",
        "pages": 283,
        "published": 1974,
        "dateread": dates,
        "customlists": [],
    },
    {
        "id": 111,
        "bookcover": "https://m.media-amazon.com/images/I/71x0X-NfYAL._SL1500_.jpg",
        "title": "The Complete Peanuts Vol.1: 1950-1952",
        "author": "Charles Schulz",
        "genre": "comic strip",
        "format": "harcover",
        "language": "english",
        "toread": true,
        "fav": false,
        "owned": true,
        "summary": "This first volume, covering the first two and a quarter years of the strip, will be of particular fascination toPeanuts aficionados worldwide: Although there have been literally hundreds of Peanuts books published, many of the strips from the series' first two or three years have never been collected before―in large part because they showed a young Schulz working out the kinks in his new strip and include some characterizations and designs that are quite different from the cast we're all familiar with. (Among other things, three major cast members―Schroeder, Lucy, and Linus―initially show up as infants and only grow into their final mature selves as the months go by. Even Snoopy debuts as a puppy!) Thus The Complete Peanuts offers a unique chance to see a master of the art form refine his skills and solidify his universe, day by day, week by week, month by month.",
        "pages": 356,
        "published": 2004,
        "dateread": dates,
        "customlists": [],
    },

let lists = [
    {name: "Para dormir",description: "Por la noche",id: "10",booksInList: [] },
    {name: "Para despertar",description: "Por la mañana",id: "20",booksInList: [{id:1}]}
]


]);
db.myCollection.


db.getCollection(myCollection).find();
